/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as MaterialsIndexRouteImport } from './routes/materials/index'
import { Route as MaterialsSlugRouteImport } from './routes/materials/$slug'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIndexRoute = MaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsSlugRoute = MaterialsSlugRouteImport.update({
  id: '/materials/$slug',
  path: '/materials/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/shop': typeof ShopRoute
  '/materials/$slug': typeof MaterialsSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/materials/': typeof MaterialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/shop': typeof ShopRoute
  '/materials/$slug': typeof MaterialsSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/materials': typeof MaterialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/shop': typeof ShopRoute
  '/materials/$slug': typeof MaterialsSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/materials/': typeof MaterialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/shop'
    | '/materials/$slug'
    | '/product/$handle'
    | '/materials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/shop'
    | '/materials/$slug'
    | '/product/$handle'
    | '/materials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/shop'
    | '/materials/$slug'
    | '/product/$handle'
    | '/materials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ShopRoute: typeof ShopRoute
  MaterialsSlugRoute: typeof MaterialsSlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
  MaterialsIndexRoute: typeof MaterialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/': {
      id: '/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof MaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$slug': {
      id: '/materials/$slug'
      path: '/materials/$slug'
      fullPath: '/materials/$slug'
      preLoaderRoute: typeof MaterialsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ShopRoute: ShopRoute,
  MaterialsSlugRoute: MaterialsSlugRoute,
  ProductHandleRoute: ProductHandleRoute,
  MaterialsIndexRoute: MaterialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
