/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DesignWithAiRouteImport } from './routes/design-with-ai'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CollectionsCategoryRouteImport } from './routes/collections.$category'
import { Route as DesignWithAiIndexRouteImport } from './routes/design-with-ai.index'
import { Route as DesignWithAiThreadIdRouteImport } from './routes/design-with-ai.$threadId'
import { Route as MaterialsIndexRouteImport } from './routes/materials/index'
import { Route as MaterialsSlugRouteImport } from './routes/materials/$slug'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignWithAiRoute = DesignWithAiRouteImport.update({
  id: '/design-with-ai',
  path: '/design-with-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCategoryRoute = CollectionsCategoryRouteImport.update({
  id: '/collections/$category',
  path: '/collections/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignWithAiIndexRoute = DesignWithAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesignWithAiRoute,
} as any)
const DesignWithAiThreadIdRoute = DesignWithAiThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => DesignWithAiRoute,
} as any)
const MaterialsIndexRoute = MaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsSlugRoute = MaterialsSlugRouteImport.update({
  id: '/materials/$slug',
  path: '/materials/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/design-with-ai': typeof DesignWithAiRouteWithChildren
  '/shop': typeof ShopRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/design-with-ai/$threadId': typeof DesignWithAiThreadIdRoute
  '/materials/$slug': typeof MaterialsSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/design-with-ai/': typeof DesignWithAiIndexRoute
  '/materials/': typeof MaterialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/shop': typeof ShopRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/design-with-ai/$threadId': typeof DesignWithAiThreadIdRoute
  '/materials/$slug': typeof MaterialsSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/design-with-ai': typeof DesignWithAiIndexRoute
  '/materials': typeof MaterialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/design-with-ai': typeof DesignWithAiRouteWithChildren
  '/shop': typeof ShopRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/design-with-ai/$threadId': typeof DesignWithAiThreadIdRoute
  '/materials/$slug': typeof MaterialsSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/design-with-ai/': typeof DesignWithAiIndexRoute
  '/materials/': typeof MaterialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/design-with-ai'
    | '/shop'
    | '/collections/$category'
    | '/design-with-ai/$threadId'
    | '/materials/$slug'
    | '/product/$handle'
    | '/design-with-ai/'
    | '/materials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/shop'
    | '/collections/$category'
    | '/design-with-ai/$threadId'
    | '/materials/$slug'
    | '/product/$handle'
    | '/design-with-ai'
    | '/materials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/design-with-ai'
    | '/shop'
    | '/collections/$category'
    | '/design-with-ai/$threadId'
    | '/materials/$slug'
    | '/product/$handle'
    | '/design-with-ai/'
    | '/materials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DesignWithAiRoute: typeof DesignWithAiRouteWithChildren
  ShopRoute: typeof ShopRoute
  CollectionsCategoryRoute: typeof CollectionsCategoryRoute
  MaterialsSlugRoute: typeof MaterialsSlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
  MaterialsIndexRoute: typeof MaterialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-with-ai': {
      id: '/design-with-ai'
      path: '/design-with-ai'
      fullPath: '/design-with-ai'
      preLoaderRoute: typeof DesignWithAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$category': {
      id: '/collections/$category'
      path: '/collections/$category'
      fullPath: '/collections/$category'
      preLoaderRoute: typeof CollectionsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-with-ai/': {
      id: '/design-with-ai/'
      path: '/'
      fullPath: '/design-with-ai/'
      preLoaderRoute: typeof DesignWithAiIndexRouteImport
      parentRoute: typeof DesignWithAiRoute
    }
    '/design-with-ai/$threadId': {
      id: '/design-with-ai/$threadId'
      path: '/$threadId'
      fullPath: '/design-with-ai/$threadId'
      preLoaderRoute: typeof DesignWithAiThreadIdRouteImport
      parentRoute: typeof DesignWithAiRoute
    }
    '/materials/': {
      id: '/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof MaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$slug': {
      id: '/materials/$slug'
      path: '/materials/$slug'
      fullPath: '/materials/$slug'
      preLoaderRoute: typeof MaterialsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DesignWithAiRouteChildren {
  DesignWithAiThreadIdRoute: typeof DesignWithAiThreadIdRoute
  DesignWithAiIndexRoute: typeof DesignWithAiIndexRoute
}

const DesignWithAiRouteChildren: DesignWithAiRouteChildren = {
  DesignWithAiThreadIdRoute: DesignWithAiThreadIdRoute,
  DesignWithAiIndexRoute: DesignWithAiIndexRoute,
}

const DesignWithAiRouteWithChildren = DesignWithAiRoute._addFileChildren(
  DesignWithAiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DesignWithAiRoute: DesignWithAiRouteWithChildren,
  ShopRoute: ShopRoute,
  CollectionsCategoryRoute: CollectionsCategoryRoute,
  MaterialsSlugRoute: MaterialsSlugRoute,
  ProductHandleRoute: ProductHandleRoute,
  MaterialsIndexRoute: MaterialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
